### ISSUE TITLE
[BUG] $Ping command is shutting down the bot

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#103]
2020-10-09T14:31:08.410764+00:00 app[worker.1]: /app/src/commands/ping.js:17
2020-10-09T14:31:08.410783+00:00 app[worker.1]: } catch (error) {
2020-10-09T14:31:08.410784+00:00 app[worker.1]: ^^^^^
2020-10-09T14:31:08.410784+00:00 app[worker.1]: 
2020-10-09T14:31:08.410785+00:00 app[worker.1]: SyntaxError: Unexpected token 'catch'
2020-10-09T14:31:08.410785+00:00 app[worker.1]: at compileFunction (<anonymous>)
2020-10-09T14:31:08.410786+00:00 app[worker.1]: at wrapSafe (internal/modules/cjs/loader.js:931:16)
2020-10-09T14:31:08.410786+00:00 app[worker.1]: at Module._compile (internal/modules/cjs/loader.js:979:27)
2020-10-09T14:31:08.410786+00:00 app[worker.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
2020-10-09T14:31:08.410787+00:00 app[worker.1]: at Module.load (internal/modules/cjs/loader.js:879:32)
2020-10-09T14:31:08.410787+00:00 app[worker.1]: at Function.Module._load (internal/modules/cjs/loader.js:724:14)
2020-10-09T14:31:08.410787+00:00 app[worker.1]: at Module.require (internal/modules/cjs/loader.js:903:19)
2020-10-09T14:31:08.410788+00:00 app[worker.1]: at require (internal/modules/cjs/helpers.js:74:18)
2020-10-09T14:31:08.410788+00:00 app[worker.1]: at module.exports (/app/src/handlers/command.js:10:16)
2020-10-09T14:31:08.410788+00:00 app[worker.1]: at /app/src/index.js:15:37
2020-10-09T14:31:08.410789+00:00 app[worker.1]: at Array.forEach (<anonymous>)
2020-10-09T14:31:08.410789+00:00 app[worker.1]: at Object.<anonymous> (/app/src/index.js:14:13)
2020-10-09T14:31:08.410789+00:00 app[worker.1]: at Module._compile (internal/modules/cjs/loader.js:1015:30)
2020-10-09T14:31:08.410790+00:00 app[worker.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
2020-10-09T14:31:08.410790+00:00 app[worker.1]: at Module.load (internal/modules/cjs/loader.js:879:32)
2020-10-09T14:31:08.410790+00:00 app[worker.1]: at Function.Module._load (internal/modules/cjs/loader.js:724:14)
2020-10-09T14:31:08.529644+00:00 heroku[worker.1]: Process exited with status 1

**Comment by hyonim** [comment]
~~Wait, let me fix.~~ Fixed.
